services:
  auth_db:
    image: postgres:17-alpine
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - ./environment/auth_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network
  
  migrate_auth:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      auth_db: { condition: service_healthy }
    volumes:
      - ./backend/LoginService/migrations:/migrations
    command: >
      -path /migrations
      -database "postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth_db:5432/${AUTH_DB}?sslmode=disable"
      up
    networks: [app_network]

  employee_db:
    image: postgres:17-alpine
    container_name: employee_service_db
    restart: always
    environment:
      POSTGRES_USER: ${EMPL_DB_USER}
      POSTGRES_PASSWORD: ${EMPL_DB_PASSWORD}
      POSTGRES_DB: ${EMPL_DB}
    ports:
      - "${EMPL_DB_PORT}:5432"
    volumes:
      - ./environment/empl_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${EMPL_DB_USER} -d ${EMPL_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network
    
  migrate_employee:
      image: migrate/migrate
      entrypoint: ["migrate"]
      depends_on:
        employee_db: { condition: service_healthy }
      volumes:
        - ./backend/EmployeeService/migrations:/migrations
      command: >
        -path /migrations
        -database "postgres://${EMPL_DB_USER}:${EMPL_DB_PASSWORD}@employee_db:5432/${EMPL_DB}?sslmode=disable"
        up
      networks: [app_network]
  
  nats:
    image: nats:2.10-alpine
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--js", "--sd=/data", "--http_port=8222"]
    volumes:
      - nats-data:/data
    restart: always

  nats-setup:
    image: natsio/nats-box:0.17.1
    container_name: nats-jetstream-setup
    depends_on:
      - nats
    entrypoint: ["sh", "-c"]
    command: >
      until nats --server nats:4222 server check >/dev/null 2>&1; do sleep 1; done
      if ! nats --server nats:4222 stream info employee-events >/dev/null 2>&1; then
        nats --server nats:4222 stream add employee-events --storage file --retention limits --subjects employee.event.* --max-msgs -1
      fi
      if ! nats --server nats:4222 stream info project-events >/dev/null 2>&1; then
        nats --server nats:4222 stream add project-events --storage file --retention limits --subjects project.* --subjects task.* --max-msgs -1
      fi
      if ! nats --server nats:4222 stream info login-commands >/dev/null 2>&1; then
        nats --server nats:4222 stream add login-commands --storage file --retention limits --subjects login.command.deactivate --max-msgs -1
      fi
    restart: "no"
    networks:
      - app_network

  project_db:
    image: postgres:17-alpine
    container_name: project_service_db
    restart: always
    environment:
      POSTGRES_USER: ${PROJECT_DB_USER}
      POSTGRES_PASSWORD: ${PROJECT_DB_PASSWORD}
      POSTGRES_DB: ${PROJECT_DB}
    ports:
      - "${PROJECT_DB_PORT}:5432"
    volumes:
      - ./environment/project_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROJECT_DB_USER} -d ${PROJECT_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network
  
  migrate_project:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      project_db: { condition: service_healthy }
    volumes:
      - ./backend/ProjectService/migrations:/migrations
    command: >
      -path /migrations
      -database "postgres://${PROJECT_DB_USER}:${PROJECT_DB_PASSWORD}@project_db:5432/${PROJECT_DB}?sslmode=disable"
      up
    networks: [app_network]
  
  analytics_db:
    image: postgres:17-alpine
    container_name: analytics_service_db
    restart: always
    environment:
      POSTGRES_USER: ${ANALYTICS_DB_USER}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      POSTGRES_DB: ${ANALYTICS_DB}
    ports:
      - "${ANALYTICS_DB_PORT}:5432"
    volumes:
      - ./environment/analytics_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ANALYTICS_DB_USER} -d ${ANALYTICS_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  analytics_redis:
    image: redis:7
    container_name: analytics_cache
    restart: always
    ports:
      - "${ANALYTICS_REDIS_PORT}:6379"
    volumes:
      - ./environment/analytics_redis:/data
    networks:
      - app_network

  migrate_analytics:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      analytics_db: { condition: service_healthy }
    volumes:
      - ./backend/AnalyticsService/migrations:/migrations
    command: >
      -path /migrations
      -database "postgres://${ANALYTICS_DB_USER}:${ANALYTICS_DB_PASSWORD}@analytics_db:5432/${ANALYTICS_DB}?sslmode=disable"
      up
    networks: [app_network]

volumes:
  nats-data:

networks:
  app_network:
    driver: bridge