services:
  auth_db:
    image: postgres:17-alpine
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - ./environment/auth_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network
  
  redis_sessions:
    image: redis:7
    container_name: auth_session_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./environment/redis_sessions:/data
    networks:
      - app_network

  migrate_auth:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      auth_db: { condition: service_healthy }
    volumes:
      - ./LoginService/migrations:/migrations
    command: >
      -path /migrations
      -database "postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth_db:5432/${AUTH_DB}?sslmode=disable"
      up
    networks: [app_network]

  employee_db:
    image: postgres:17-alpine
    container_name: employee_service_db
    restart: always
    environment:
      POSTGRES_USER: ${EMPL_DB_USER}
      POSTGRES_PASSWORD: ${EMPL_DB_PASSWORD}
      POSTGRES_DB: ${EMPL_DB}
    ports:
      - "${EMPL_DB_PORT}:5432"
    volumes:
      - ./environment/empl_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${EMPL_DB_USER} -d ${EMPL_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
    networks:
      - app_network
    
  migrate_employee:
      image: migrate/migrate
      entrypoint: ["migrate"]
      depends_on:
        employee_db: { condition: service_healthy }
      volumes:
        - ./EmployeeService/migrations:/migrations
      command: >
        -path /migrations
        -database "postgres://${EMPL_DB_USER}:${EMPL_DB_PASSWORD}@employee_db:5432/${EMPL_DB}?sslmode=disable"
        up
      networks: [app_network]
  
  nats:
    image: nats:2.10-alpine
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--js", "--sd=/data", "--http_port=8222"]
    volumes:
      - nats-data:/data
    restart: unless-stopped

volumes:
  nats-data:

networks:
  app_network:
    driver: bridge