services:
  identity_db:
    image: postgres:17-alpine
    container_name: identity_db
    restart: always
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity -d identity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  business_db:
    image: postgres:17-alpine
    container_name: business_db
    restart: always
    environment:
      POSTGRES_USER: business
      POSTGRES_PASSWORD: business
      POSTGRES_DB: business
    ports:
      - "5435:5432"
    volumes:
      - business_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U business -d business"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  migrate_identity:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      identity_db:
        condition: service_healthy
    volumes:
      - ./migrations/identity:/migrations
    command: >
      -path /migrations
      -database "postgres://identity:identity@identity_db:5432/identity?sslmode=disable"
      up
    networks:
      - app_network

  migrate_business:
    image: migrate/migrate
    entrypoint: ["migrate"]
    depends_on:
      business_db:
        condition: service_healthy
    volumes:
      - ./migrations/business:/migrations
    command: >
      -path /migrations
      -database "postgres://business:business@business_db:5432/business?sslmode=disable"
      up
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  identity_data:
  business_data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge
