syntax = "proto3";

package employees;

option go_package = "github.com/foksdanilka34-maker/F5ProjectUsersControl/employeess/v1;employeesv1";

import "google/protobuf/empty.proto";

service EmployeeService {
    rpc CreateProfile(CreateProfileRequest) returns (Profile);
    rpc GetProfile(GetProfileRequest) returns (Profile);
    rpc ListProfiles(ListProfilesRequest) returns (ListProfilesResponse);
    rpc UpdateProfile(UpdateProfileRequest) returns (Profile);
    rpc DeactivateProfile(DeactivateProfileRequest) returns (google.protobuf.Empty);
}

message Profile {
    string id = 1;
    string first_name = 2;
    string last_name = 3;
    string position_id = 4;
    string email = 5;
    string avatar_url = 6;
    string hire_date = 7;
    Department department = 8;
    repeated Skill skills = 9;
    string login = 10;
    string role = 11;
    string created_at = 12;
    string updated_at = 13;
    bool is_active = 14;
}

message Department {
    string id = 1;
    string name = 2;
}

message Skill {
    string id = 1;
    string name = 2;
}

message CreateProfileRequest {
    string first_name = 1;
    string last_name = 2;
    string position_id = 3;
    string email = 4;
    optional string department_id = 5;
    string hire_date = 6;

    string login = 7;
    string password = 8;
    string role = 9;
}

message GetProfileRequest {
    string user_id = 1;
}

message ListProfilesRequest {
    int32 page_size = 1;
    int32 page_number = 2;
    string department_id = 3;
    string position_id = 4;
}

message ListProfilesResponse {
    repeated Profile profiles = 1;
    int32 total_count = 2;
}

message UpdateProfileRequest {
    string user_id = 1;
    optional string first_name = 2;
    optional string last_name = 3;
    optional string position_id = 4;
    optional string email = 5;
    optional string department_id = 6;
    optional string avatar_url = 7;
    optional string hire_date = 8;
}

message DeactivateProfileRequest {
    string user_id = 1;
}
